name: Push docker images
on:
  push:
    branches:
      - hack-git-clone
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+

jobs:
  push-core-image:
    name: Push dependabot-core image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull Docker base image & warm Docker cache
        run: |
          docker pull "dependabot/dependabot-core:latest"
      - name: Build dependabot-core image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
            -t "dependabot/dependabot-core:latest" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
      - name: Log in to the Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # - name: Push image to packages (latest)
      #   if: "!contains(github.ref, 'refs/tags')"
      #   run: |
      #     docker push "dependabot/dependabot-core:latest"
      - name: Push image to packages (tagged)
        # if: "contains(github.ref, 'refs/tags')"
        run: |
          docker tag "dependabot/dependabot-core:latest" "dependabot/dependabot-core:vendor-dependencies"
          docker push "dependabot/dependabot-core:vendor-dependencies"
